chat_app/chat_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('chat_room.urls', namespace='chat_room')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat_app/chat_room/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'chat_room'

urlpatterns = [    
    path('', home, name='home'),
    path('index/', index, name='index'),
    path('chat_person/', chat_person, name='chat_person'),
    path('searchhandle/',searchhandle,name='searchhandle'),
    path('search/',autocompletion,name='autocompletion'),
    path('fileshare/',fileshare,name='fileshare'),
    path('upload/',upload,name='upload'),
    path('temp/',temp,name="temp")

]

chat_app/main/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'main'
# main:login
urlpatterns = [
    path('login/', login_page, name='login'),
    path('signup/', signup, name='signup'),
    path('signhandle/', signhandle, name = 'signhandle'),
    path('loginauth/', loginauth, name = 'loginauth'),
    path('change_password/', change_password, name = 'change_password'),
    path('otp/', otp, name='otp'),
    path('verify_otp/', verify_otp, name='verify_otp'),
    path('new_password/', new_password, name='new_password'),
    path('send_friend_request/<int:userID>/', sent_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:requestID>/', accept_friend_request, name='accept_friend_request'),
    path('friend_list/', friend_list, name='friend_list'),
    path('sentrequests/',sentrequests,name='sentrequests'),
    path('recievedrequests/', recievedrequests, name='recievedrequests'),
    
    path('searchhandle/',searchhandle,name='searchhandle'),
    path('search/',autocompletion,name='autocompletion')
]

chat_app/main/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import BaseUserManager

class UserProfileManager(BaseUserManager):
    """Manager for user profiles"""

    def create_user(self, email, fname, lname, dob, password=None):
        """Creates a new user profile"""
        if not email:
            raise ValueError('Users must have an email address')

        email = self.normalize_email(email)
        user = self.model(email=email, fname=fname, lname=lname, dob=dob)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, email, fname, lname, dob, password):
        """Creates a new superuser with given details"""
        user = self.create_user(email, fname, lname, dob, password)
        user.is_superuser = True

        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    """DataBase models for users in the systems"""
    email = models.EmailField(max_length=255, unique=True)
    fname = models.CharField(max_length=255)
    lname = models.CharField(max_length=255)
    dob = models.DateField()
    profile_pic = models.ImageField(upload_to='profile_pic/%Y/%m/%d/', default='images/default_profile_pic.png')
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    otp = models.IntegerField(blank=True, null=True)
    friends = models.ManyToManyField("User", blank=True)

    objects = UserProfileManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['fname', 'lname', 'dob']

    def get_full_name(self):
        """Retrive full name of user"""
        return self.fname + " " + self.lname

    def get_short_name(self):
        """Retrive short name of user"""
        return self.fname

    def get_email(self):
        """Retrieves email of user"""
        return self.email

    def get_dob(self):
        """Retrieves dob of user"""
        return self.dob

    def __str__(self):
        """Return string representation of our user"""
        return self.email

    def get_username(self):
        """Returns username by dividing email"""
        return self.email.split('@')[0]

class UserRelationShip(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user_chat', on_delete=models.CASCADE)
    to_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='to_user_chat')
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returns representation of relation between users"""
        return f"{self.from_user.get_full_name()} -> {self.to_user.get_full_name()}"

chat_app/main/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.contrib.messages.api import warning
from django.forms import widgets
from .models import *
User = get_user_model()

class RegisterForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['fname', 'lname','dob', 'email','password','password_2']
        widgets = {
                'fname' : forms.TextInput(attrs={'type' : "text", "class" : "form-control" 
                ,"aria-describedby" : "fname", "placeholder" : "First Name " ,"name" :"fname"}),
                'lname' : forms.TextInput(attrs={'type' : "text", "class" : "form-control" 
                ,"aria-describedby" : "lname", "placeholder" : "Last Name" ,"name" :"lname"}),
                'email' : forms.TextInput(attrs={'type' : "email", "class" : "form-control" 
                ,"aria-describedby" : "email", "placeholder" : "Enter email" ,"name" :"email"}),
                'password': forms.PasswordInput(attrs={'type' : "password", "class" : "form-control" 
                ,"aria-describedby" : "password", "placeholder" : "password" ,"name" :"password"}),
                'password_2': forms.PasswordInput(attrs={'type' : "password", "class" : "form-control" 
                ,"aria-describedby" : "password_2", "placeholder" : "password" ,"name" :"password-2"}),
                'dob' : forms.DateInput(attrs={'type' : "date", "class" : "form-control", 'required pattern' : "\d{4}-\d{2}-\d{2}" 
                ,"aria-describedby" : "dob", "placeholder" : "yyyy-mm-dd" ,"name" :"dob" ,'min':'1959-01-01'})
        }
    
    def clean_email(self):
        """
        Verify email is available
        """
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("Email already exists")
        return email
    
    def clean(self):
        """
        Verify both passwords match.
        """
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password_2 = cleaned_data.get('password_2')
        if password is not None and password != password_2:
            self.add_error('password_2', "Your passwords must match")
        return cleaned_data
        

chat_app/main/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages 
from django.contrib.auth import authenticate, login, get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User 
from .forms import *
import json
from django.contrib.auth import get_user_model

User = get_user_model()

from django.conf import settings
from .models import *
from .helpers import *

from django.http import JsonResponse



# Create your views here.
def login_page(request):
    return render(request,'main/login.html')

def loginauth(request):
    if request.method == 'POST':
        e_id = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=e_id, password=password)
        if user is not None:
            login(request, user)
            return redirect('chat_room:home')
        else:
            messages.info(request,'Invalid Credentials')
            return redirect('main:login')
    else:
        return redirect('main:login')

def home(request):
    return render(request,'chat_room/home.html')

def autocompletion(request):
    User = get_user_model()
    user = request.GET.get('email')
    emails = []
    # print(user)
    if user:
        user_objs = User.objects.filter(email__contains = user)
        for obj in user_objs:
            emails.append((obj.email))
        # print(emails)
    return JsonResponse({'status':200,'data':emails},safe=False)


def signup(request):
    form = RegisterForm
    para = {
        'form':form
    }
    return render(request, 'main/form.html', context=para)

def signhandle(request):
    if request.method == "POST":
        # Get the post parameters
        email = request.POST['email']
        fname = request.POST['fname']
        lname = request.POST['lname']
        pass1 = request.POST['password']
        pass2 = request.POST['password_2']
        dob = request.POST['dob']

        if (pass1!= pass2):
             messages.error(request, " Passwords do not match")
             return redirect('main:signup')
        myuser = User.objects.create_user(email=email, fname=fname, lname=lname, dob=dob, password=pass1)
        myuser.save()
        messages.success(request, " account has been successfully created")
        return redirect('main:login')
    else:
        return redirect('home')

def searchhandle(request):
    if request.method == 'POST':
        email_or_name = request.POST['email']
        user_list = User.objects.filter(email__icontains=email_or_name)
        print(user_list)
        return render(request,'chat_room/results.html', context={'user_list': user_list})
    else:
        return redirect('home')

def change_password(request):
    return render(request, 'main/change_password.html')

def otp(request):
    email = request.POST['email']
    otp = generate_otp()
    try:
        user = User.objects.get(email=email)
    except:
        messages.error(request, "User not found")
    user.otp = otp
    user.save()
    subject, message = generate_otp_mail_fields(otp, user.fname)
    send_mail_helper(subject, message, user.email)
    return render(request, 'main/otp.html', {'email': user.email})

def verify_otp(request):
    if request.method == 'POST':
        otp = request.POST.get('my_otp')
        email = request.POST.get('email')
        user = User.objects.get(email=email)
        if str(user.otp) == otp:
            return render(request, 'main/new_password.html', {'email': email})
        else:
            error_message = 'Wrong Otp! Please Try Again.'
            return render(request, 'main/otp.html', {'email': email, 'error': error_message})
    else:
        return redirect('main:login')

def new_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password_1')
        password_2 = request.POST.get('password_2')
        if password == password_2:
            user = User.objects.get(email=email)
            user.set_password(password)
            user.save()
            return render(request, 'main/password_changed.html')
        else:
            return render(request, 'main/new_password.html', {'email': email})
    else:
        return redirect('main:login')

def sentrequests(request):
    user = get_user_model()
    all_users = user.objects.all()
    if request.method == 'POST':
        return render(request,'main/add_friends.html', {'allusers': all_users })
    else:
        return redirect('home')


# ----- Creating Views for friend request -------
@login_required
def sent_friend_request(request, userID):
    """Send friend request"""
    from_user = request.user
    to_user = User.objects.get(id=userID)
    friend_request, created = UserRelationShip.objects.get_or_create(from_user=from_user, to_user=to_user)
    if created:
        return render(request, 'main/all_change_redirect.html', {'change': 'Friend request sent'})
    else:
        return render(request, 'main/all_change_redirect.html', {'change': 'Friend request was already sent'})

@login_required
def accept_friend_request(request, requestID):
    """Accept friend request"""
    friend_request = UserRelationShip.objects.get(id=requestID)
    if friend_request.to_user == request.user:
        friend_request.to_user.friends.add(friend_request.from_user)
        friend_request.from_user.friends.add(friend_request.to_user)
        friend_request.delete()
        return render(request, 'main/all_change_redirect.html', {'change': 'Friend Request accepted'})
    else:
        return render(request, 'main/all_change_redirect.html', {'change': 'Friend Request not accepted'})

@login_required
def friend_list(request):
    """Returns Friend List page"""
    user_db = User.objects.get(email=request.user)
    all_friends = user_db.friends.all()
    return render(request, 'main/current_friends.html', {
        'all_friends': all_friends
    })

@login_required
def recievedrequests(request):
    user = request.user
    all_friend_requests = UserRelationShip.objects.filter(to_user=user)
    return render(request, 'main/friends_requests.html', {
        'all_friend_requests': all_friend_requests, 
    })

chat_app/main/templates/main/add_friends.html
{% extends 'base.html' %}

{% block title %} 
    Send request
{% endblock %}

{% block body %} 

{% comment %} Writing friend request logic {% endcomment %}
<h1>To send friend request</h1>
{% for users in allusers %}
    {% comment %} {% if not user.is_superuser %}
        {% if user not in request.users.friends.all and user != request.user %} {% endcomment %}
            <h3>{{ users.fname }} <a href="{% url 'send_friend_request' userID=users.id %}">Send friend request</a></h3>
        {% comment %} {% endif %}
    {% endif %} {% endcomment %}
{% endfor %}

{% endblock %}

chat_app/main/templates/main/all_change_redirect.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
{{ change }}
{% endblock %}

{% block css_file %}
<link rel="stylesheet" href="{% static 'chat_room/results.css' %}">
{% endblock css_file %}


{% block body %}
<div id='wrapper'>
    <h2>{{ change }} </h2>
    <div class="friend-wrapper">
        <p class='left'>Redirecting in <span id='timer'></span> seconds</p>
        <p><a class='btn btn-danger' href="{% url 'chat_room:home' %}">Click here</a> to go to login page</p>
    </div>
</div>
<script>
    var time = 5;
    var interval = setInterval(function() {
        time--;
        if (time == 0) {
            clearInterval(interval);
            window.location.href = "{% url 'chat_room:home' %}";
        }
        document.getElementById('timer').innerHTML = time;
    }, 1000);    
</script>
{% endblock %}

chat_app/main/templates/main/change_password.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} Change My Password {% endblock title %} 

{% block css_file %}
<link rel="stylesheet" href="{% static 'main/change_password.css' %}"> 
{% endblock css_file %}

{% block body %}
<div class="d-flex justify-content-center">
    <form action="{% url "main:otp" %}" method="post">
        {% csrf_token %}
        <h4>Forgot Password</h4>
        <label for="email">Please enter your registered e-mail: </label>
        <input placeholder="Email" id="email" type="email" name="email" required>
        <div class="d-flex justify-content-center ">
        <input class="btn btn-primary" type="submit" value='Submit'>
        </div>
    </form>
</div>
{% endblock body %}

chat_app/main/templates/main/current_friends.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Friends
{% endblock %}

{% block css_file %}
<link rel="stylesheet" href="{% static 'chat_room/results.css' %}">
{% endblock %}

{% block body %}
    <div id='wrapper' class='container justify-content-center'>
        <h2>Friends List</h2>
        {% for friends in all_friends %}
            <div class="friend-wrapper">
                <div class="img">
                    <img src="/media/{{ friends.profile_pic }}" alt="">                    
                </div>
                
                <div class='left'>
                    <div class="one"><p>{{ friends.get_full_name }}</p></div>
                    <p>
                        <strong>{{ friends.email }}</strong>
                    </p>
                </div>
                <div class='right'>
                    <a class='btn btn-danger' href="{% url 'main:send_friend_request' userID=user.id %}">Friends!</a>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

chat_app/main/templates/main/form.html
{% extends 'base.html' %}

{% load static %}

{% block title %} 
    SignUp
{% endblock %}

{% block body %}
<link rel="stylesheet" href="{% static 'main/form.css' %}">

  <div class="modal-header">
    <h3 class="modal-title" id="loginModalTitle">Signup</h3>
  </div>
  <div class="d-flex justify-content-center align-items-center container-lg">
    <form method="post" action="{% url "main:signhandle" %}">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
    <div class="d-flex justify-content-center align-items-center container-lg">
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
    
{% endblock %}

chat_app/main/templates/main/friends_requests.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Friend Requests
{% endblock %}

{% block css_file %}
<link rel="stylesheet" href="{% static 'main/friend_request.css'%}">
{% endblock %}

{% block body %}
    <div id="wrapper" class='container justify-content-center'>
        <h2>Received friend request</h2>
        <br>
        {% for friend_request in all_friend_requests %}
            <div class='friend-wrapper'>
                <div class="img">
                    <img src="/media/images/default_profile_pic.png" alt="">                    
                </div>
                <div class='left'>
                    <p class='one'>{{ friend_request.from_user.get_full_name }}</p>
                    <p class='two'>{{ friend_request.from_user }}</p>
                </div>
                <div class="right">
                    <a class='btn btn-primary' href="{% url 'main:accept_friend_request' requestID=friend_request.id %}">
                        Accept Friend request</a>
                </div>
            </div>
        {% empty %}
            <h5>No friend request received.</h5>
        {% endfor %}
    </div>
{% endblock %}

chat_app/main/templates/main/login.html
{% extends 'base.html' %} 

{% load static %} 

{% block title %} 
login 
{% endblock %} 

{% block css_file %}
<link rel="stylesheet" href="{% static 'main/login.css' %}">
{% endblock %} 

{% block body %}
<div class = "container">
<div class="d-flex justify-content-center"  >
<span>
    <h5 class="modal-title" id="loginModalTitle" > Login </h5>
</span>
</div>
<div class="d-flex justify-content-center align-items-center container-lg">
    <form method="post" action="{% url "main:loginauth" %}">
        {% csrf_token %}
            <div class = "txt_field">
            <input placeholder="Email" type="text" class="form-control" name="email" required>
            </div>
            <div class = "txt_field">
            <input placeholder="Password" type="password" class="form-control" name="password" required>
            </div>
            
            <div class="d-flex justify-content-left align-items-left container-lg">
            <a style="color:#34105c"href="{% url "main:change_password" %}">Forgot Password?</a>
            </div>
            <div class="d-flex justify-content-center ">
                <input class="btn btn-primary" type="submit" name="" value="Login">
            </div> 
        <p class="d-flex justify-content-center" class="message">Not registered? <a href="http://127.0.0.1:8000/signup/"> SignUp</a></p>
    </form>
</div>

<div class="d-flex justify-content-center align-items-center container-lg">
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
            {% endfor %}
    </ul>
    {% endif %}
</div>
</div>
{% endblock %}

chat_app/main/templates/main/new_password.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    New Password
{% endblock %}

{% block css_file %}
<link rel="stylesheet" href="{% static 'main/friend_request.css'%}">
<style>
    form{
        margin: auto;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock css_file %}

{% block body %}
    <div id="wrapper"  style='margin-top: 3%;'>
        <h2>Please Enter your new password</h2>
        <div class="friend-wrapper d-flex justify-content-center align-items-center container-lg" style="margin: 15% auto ">
            <form action="{% url "main:new_password" %}" method="post">
                {% csrf_token %}
                    <label for="id_password">Password:</label>
                    <input type="password" name="password_1" required id="id_password">
                    <label for="id_password">Confirm Password:</label>
                    <input type="password" name="password_2" required id="id_password">
                <input type="hidden" name="email" value="{{ email }}">
                <input class='btn btn-danger' type="submit" value="Submit">
            </form>
        </div>
    </div>
{% endblock %}

chat_app/main/templates/main/otp.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Change My Password
{% endblock title %}

{% block css_file %}
<link rel="stylesheet" href="{% static 'chat_room/results.css' %}">
<style>
    form{
        margin: auto;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
</style>
{% endblock css_file %}


{% block body %}
    <div id="wrapper" style='margin-top: 3%;'>
        <h2>Enter OTP</h2>
        <div class='friend-wrapper' style="margin: 20% auto;">
            <form action="{% url "main:verify_otp" %}" method="post">
                <h4>Enter 6 Digits OTP</h4>
                {% if error %}
                    <p>{{ error }}</p>
                {% endif %}
                {% csrf_token %}
                <label for="my_otp">
                Note: Check spam if not received.</label>
                <input id="my_otp" type="number" name="my_otp">
                <input type="hidden" name='email' value={{ email }}>
                <input class='btn btn-danger' type="submit" value='Submit'>
            </form>
        </div>
    </div>
{% endblock body %}

chat_app/main/templates/main/password_changed.html
{% extends 'base.html' %}

{% load static%}

{% block title %}
Password changed
{% endblock %}

{% block css_file %}
<link rel="stylesheet" href="{% static 'main/password_changed.css' %}">
{% endblock %}

{% block body %}
<h2>Password Changed Succesfully </h2>
<p><a href="{% url 'main:login' %}">Click here</a> to go to login page</p>
{% endblock %}