chat_app/chat_app/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('', include('chat_room.urls', namespace='chat_room')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat_app/chat_room/urls.py
from os import name
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'chat_room'

urlpatterns = [    
    path('', home, name='home'),
    path('index/', index, name='index'),
    path('chat_person/', chat_person, name='chat_person'),
    path('searchhandle/',searchhandle,name='searchhandle'),
    path('search/',autocompletion,name='autocompletion'),
    path('fileshare/',fileshare,name='fileshare'),
    path('upload/',upload,name='upload'),
    path('temp/',temp,name="temp")

]

chat_app/main/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'main'
# main:login
urlpatterns = [
    path('login/', login_page, name='login'),
    path('signup/', signup, name='signup'),
    path('signhandle/', signhandle, name = 'signhandle'),
    path('loginauth/', loginauth, name = 'loginauth'),
    path('change_password/', change_password, name = 'change_password'),
    path('otp/', otp, name='otp'),
    path('verify_otp/', verify_otp, name='verify_otp'),
    path('new_password/', new_password, name='new_password'),
    path('send_friend_request/<int:userID>/', sent_friend_request, name='send_friend_request'),
    path('accept_friend_request/<int:requestID>/', accept_friend_request, name='accept_friend_request'),
    path('friend_list/', friend_list, name='friend_list'),
    path('sentrequests/',sentrequests,name='sentrequests'),
    path('recievedrequests/', recievedrequests, name='recievedrequests'),
    
    path('searchhandle/',searchhandle,name='searchhandle'),
    path('search/',autocompletion,name='autocompletion')
]

chat_app/chat_room/models.py
from django.db import models

from main.models import User

# Create your models here.

class Message(models.Model):
    from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.DO_NOTHING)
    to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.DO_NOTHING)
    chat_identifier = models.CharField(max_length=255)
    content = models.TextField(null=True, blank=True)
    file = models.FileField(upload_to="file/", null=True, blank=True)
    date_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['date_time']

# class Files(models.Model):
#     file = models.FileField(upload_to='file/')

chat_app/chat_room/views.py
import json
from django.shortcuts import render
from django.contrib.auth import get_user_model
from .helpers import two_username_to_one_username
from django.template.loader import render_to_string

import json
from django.contrib.auth import get_user_model
from  django.urls import reverse
from django.http import JsonResponse, request
from django.shortcuts import render, HttpResponse, redirect

from .models import Message
# Create your views here.

def home(request):
    global all_users
    user = get_user_model()
    all_users = user.objects.all()
    return render(request,'chat_room/home.html', {'allusers' : all_users })

# def chat_person(request):
#     User = get_user_model()
#     email = request.POST.get('email')
#     name = request.POST.get('name')
#     user = User.objects.get(email=email)
#     usernames = two_username_to_one_username(email, request.user.email)
#     print(usernames)
#     return render(request, 'chat_room/chat.html', {'user':user, 'name':name, 'usernames':usernames})

def chat_person(request):
    global User
    global email
    global name
    global user
    global usernames
    global messages
    User = get_user_model()
    email = request.user.email
    name = json.loads(request.body).get('id')
    user = User.objects.get(id=name)
    usernames = two_username_to_one_username(email, user.email)

    m = Message.objects.all()
    lst = []
    for message in m:
        if message.content != "":
            lst.append(("text", message.content.replace(":","").replace("1","").replace("2","").replace("3","").replace("4","").replace("5","").replace("6","").replace("7","").replace("8","").replace("9","")))
            continue
        lst.append(("file", message.file.url))
        file = lst
    # print("/n/nFILE/n/n",file)
    messages = []
    i = -1
    for obj in Message.objects.filter(chat_identifier=usernames):
        i += 1
        messages.append({ 
            'message': lst[i][1],
            'from_user': obj.from_user,
            'to_user': obj.to_user,
            'type' : lst[i][0]
        })

    print(messages)
    return render(request, 'chat_room/chat.html', {
        'user':user,
        'name':name,
        'usernames':usernames,
        'messages': messages,
        'file' : file,
        })

def index(request):
    return render(request, 'chat_room/index.html')

def searchhandle(request):
    User = get_user_model()
    if request.method == 'POST':
        email_or_name = request.POST['email']
        user_list = User.objects.filter(email__icontains=email_or_name)
        print(user_list)
        return render(request,'chat_room/results.html', context={'user_list': user_list})
    else:
        return redirect('chat_room/home.html')

def autocompletion(request):
    User = get_user_model()
    user = request.GET.get('email')
    emails = []
    # print(user)
    if user:
        user_objs = User.objects.filter(email__contains = user)
        for obj in user_objs:
            emails.append((obj.email))
        # print(emails)
    return JsonResponse({'status':200,'data':emails},safe=False)

def fileshare(request):
    return render(request, 'chat_room/upload.html')

def upload(request):
     if request.method == 'POST' and 'doc' in request.FILES:
         new_file = Message(
             file = request.FILES['doc']
         )
         new_file.save(force_insert=True)
         files = []
         files.append(new_file)
         return render(request,'chat_room/chat2.html',{'uploaded_file': new_file})
    #      render(request, 'chat_room/chat.html', {
    #       'user':user,
    #       'name':name,
    #       'usernames': usernames,
    #       'messages': messages,
    #       'uploaded_file': new_file
    #       })
    #      return render(request,'chat_room/home.html', {'allusers' : all_users })
    #  else:
    #      return render(request,'chat_room/upload.html')

# lst = []
#     ...: for message in m:
#     ...:     if message.content != "":
#     ...:         lst.append({"type" : "text","msg":message.content})
#     ...:         continue
#     ...:     lst.append({"type":"file","path":message.file})

def temp(request):
    m = Message.objects.all()
    lst = []
    for message in m:
        if message.content != "":
            lst.append(("text", message.content))
            continue
        lst.append(("file", message.file.path))
    file = lst[-3]
    messages = []
    for obj in Message.objects.filter(chat_identifier=usernames):
        messages.append({ 
            'message': obj.content.split(":")[1],
            'from_user': obj.from_user,
            'to_user': obj.to_user
        })
    print(messages)
    return render(request,'chat_room/temp.html', {'file': file})

chat_app/chat_room/templates/chat_room/card.html
<!-- <div class="card" style="width: 18rem;">
    <img class="card-img-top" src="..." alt="Card image cap">
    <div class="card-body">
        <p><a href="{{uploaded_file.file.url}}"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-down-circle" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M1 8a7 7 0 1 0 14 0A7 7 0 0 0 1 8zm15 0A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4.5a.5.5 0 0 0-1 0v5.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V4.5z"/>
          </svg></p>
    </div>
</div> -->
<h6>{{uploaded_file.file.url}}</h6>

chat_app/chat_room/templates/chat_room/chat.html
<!-- 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  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous"> -->

<div id='right-wrapper'>
    <div class='chat-head'>
        <img src="media/{{ user.profile_pic }}" alt="Profile_pic">
        <div class='chat-name'> 
            <h1 class='font-name'>{{ user.get_full_name|title }}</h1>
        </div>
    </div>

    <div style="position:relative; width:100%; height:100%;" class='d-flex justify-content-center align-items-center'>
    {% comment %} <h1 style="top: 0; position: absolute;">Chat with {{ user.get_full_name }}</h1> {% endcomment %}

        <div id="messagecontainer" style="display:block; overflow-y: auto; height:70vh; width:100vw; position: relative;" class='container'>
            {% for message in messages %}
                <br>
                {% if message.from_user == request.user %}
                <div class='righttext'>
                    {% if message.type != 'text' %}
                     <!-- <h6>"media/file/{{ file }}"</h6> -->
                     <!-- <h6>{{message.message }}</h6> -->
                     
                        <div class="card-body" >
                            
                            <h6>{{message.message}}</h8>
                            <button type="button" class="btn btn-primary">
                            <a href="{{message.message}}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-download" viewBox="0 0 16 16">
                                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                    <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                                  </svg>
                            </a>
                            </button>
                            
                        </div>
                    {% else %}
                        <h5>{{ message.message }}</h5>
                        <div class='time_label'></div>
                    {% endif %}
                </div>
                {% elif message.to_user == request.user %}
                <div class='lefttext'>
                    {% if message.type != 'text' %}
                   <!-- <h6>"media/file/{{ file }}"</h6> -->
                   <!-- <h6>{{message.message }}</h6> -->
                   
                    <div class="card-body" style="height : 10">
                        
                        <h6>{{message.message }}</h8>
                        <button type="button" class="btn btn-primary">
                        <a href="{{message.message}}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-download" viewBox="0 0 16 16">
                                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                                <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                              </svg>
                        </a>
                        </button>
                        
                    
                    </div>
                    {% else %}
                        <h5>{{ message.message }}</h5>
                        <div class='time_label'></div>
                    {% endif %}
                    </div>
                {% endif %}
                <br>
            {% endfor %}

        </div>
    </div>
    <div style="position: absolute; width: 70%;" class='d-flex justify-content-center'>
        <a href="{% url 'chat_room:fileshare' %}">
        <button type="button" class="btn btn-outline-secondary" id="myBtn">
            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor" 
            class="bi bi-file-earmark-arrow-up-fill" viewBox="0 0 16 16">
                <path d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0zM9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1zM6.354 9.854a.5.5 0 0 1-.708-.708l2-2a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 8.707V12.5a.5.5 0 0 1-1 0V8.707L6.354 9.854z"/>
            </svg>
        </button>
        </a> 
        
    

        <input id="messageinputfield" class='form-control' style='text-align: center;' type="text" name=''>
        <input id="sendbutton" class='btn btn-primary' type='submit' value="Send">
    </div>

</div>

<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
<script type="text/javascript">
   
    const chatSocket = new WebSocket('ws://'+ window.location.host
                                     +'/ws/users/{{ usernames }}/{{ request.user.id }}/{{ user.id }}');
    console.log("{{ usernames }}");
    document.querySelector('#sendbutton').onclick = function(e){
        const message = "{{ request.user.id }}: " + document.querySelector('#messageinputfield').value;
        chatSocket.send(JSON.stringify({'message': message}));
        document.querySelector('#messageinputfield').value = "";
    }


    document.querySelector('#uploadbutton').onclick = function(e){
        const message = "{{ request.user.id }}: " + document.querySelector('#messageinputfield').value;
        chatSocket.send(JSON.stringify({'message': message}));
        document.querySelector('#messageinputfield').value = "";
    }
    
    document.querySelector('#messageinputfield').onkeyup = function(e){
        if(e.keyCode === 13){
            document.querySelector('#sendbutton').click();
        }
    }
    
    function scrollToBottom(){
        document.querySelector('#messagecontainer').scrollTo({top: document.querySelector('#messagecontainer').scrollHeight, behavior: 'smooth'});
    }
    
    chatSocket.onmessage = function(e){
        const data = JSON.parse(e.data);
        if (data.user == parseInt("{{ request.user.id }}")) {
            document.querySelector('#messagecontainer').innerHTML += '<div class="righttext">'+ data.message + '</div> <br><br>';
        } else {
            document.querySelector('#messagecontainer').innerHTML += '<div class="lefttext">'+ data.message + '</div> <br><br>';
        }
        scrollToBottom();
    }

    $('document').ready(function (){
        scrollToBottom();
    });  
    
</script>

chat_app/chat_room/templates/chat_room/chat2.html
<!-- {% extends 'base.html' %}

{% block title %}
''
{% endblock title %}

{% block body %} -->

<div class="card rounded border border-info" style="width: 22rem; height: auto ; background-color: rgb(224, 251, 255);">
    <div class="card-body">
        <p>
        <h6>{{uploaded_file.file.name}}</h8>
        <button type="button" class="btn btn-primary">
        <a href="{{uploaded_file.file.url}}">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-download" viewBox="0 0 16 16">
                <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
              </svg>
        </a>
        </button>
        </p>
    </div>
</div>

<!-- {% endblock body %}  -->

chat_app/chat_room/templates/chat_room/home.html
{% extends 'base.html' %}
{% load static %}
{% block stylesheet %}
    background-color: "#fffdd0";
{% endblock %}


{% block title %}
    DoChat - Home
{% endblock %}

{% block css_file %}
    <link rel="stylesheet" href="{% static 'chat_room/home.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock css_file %}

{% block body %} 
<script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <nav class="navbar navbar-light bg-light">
        <div class="container-fluid">
            
            <div class='profile'>
                <img src="media/{{ request.user.profile_pic}}" alt="UserIMG">
                <h4>{{ request.user.get_full_name }}</h4>
            </div>
            <form class="d-flex order-1" autocomplete="off" method="post" action="{% url 'main:searchhandle' %}">
                {% csrf_token %}
                <div class='autocomplete' id="autocomplete" style="width:800px;">
                    <input style="padding-left:50px;" class="form-control autocomplete-input" type="text" placeholder="Search" aria-label="Search" name='email'>
                <ul class="autocomplete-result-list"></ul>
            </div>
                <button class="btn btn-outline-success color-button" type="submit">Search</button>
            </form>

           

            <form class="d-flex order-2" method="post" action="{% url 'main:friend_list' %}">
                {% csrf_token %}
                <button class="btn btn-outline-success color-button" type="submit">Friends</button>
            </form>

            <form class="d-flex order-2" method="post" action="{% url 'main:recievedrequests' %}">
                {% csrf_token %}
                <button class="btn btn-outline-success color-button" type="submit">Friend Requests</button>
            </form>
        
            <div class='background'>
                <div class='wrapper'>
                    <section class='left'>
                        
                        {% comment %} <div class='wrap-search'>
                            <div class='search'>
                                <span class='fa fa-search'></span>
                                <input type="text" class='input-search' placeholder="Enter name">
                            </div>
                        </div> {% endcomment %}
                        <div class='friends'>
                            {% for friend in request.user.friends.all %}
                                <div class='friend' id="{{ friend.id }}">
                                    <div class='contact-preview'>
                                        <img src="media/{{ request.user.profile_pic}}" alt="UserIMG">
                                        <div class='contact-text'>
                                            <h1 class='font-name'>{{ friend.get_full_name }}</h1>
                                            <p class='font-preview'>{{ friend.email }}</p>
                                        </div>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </section>
                    <section class='right'>
                        <div class='chat_box'>
                            <div class='d-flex justify-content-center' id='img-text-wrapper'>
                                <div id="initial-wrapper">
                                    <img src="media/background.png"  alt="">
                                </div>
                                <h3>DoChat</h3>
                                {% comment %} <h1>Welcome to DoChat</h1> {% endcomment %}
                            </div>
                        </div>
                    </section>
                </div>
            </div>
        </div>
    </nav>
    {% comment %} {% else %} {% endcomment %}
    {% comment %} <div id='log-in-wrapper'>
        <a id='log-in' href="{% url 'main:login' %}">Log In</a>
    </div>
    {% endif %} {% endcomment %}

    <script src="https://unpkg.com/@trevoreyre/autocomplete-js"></script>
    
    <script>
        {% if not user.is_authenticated %}
        window.location.replace("{% url 'main:login' %}");
        {% endif %}
        new Autocomplete("#autocomplete",{
            search :input =>{
                console.log(input)
                const url = `/search/?email=${(input)}`
                return new Promise(resolve =>{
                    fetch(url)
                    .then(response => response.json())
                    .then(data => {
                        console.log(data)
                        resolve(data.data)
                    })
                })
            }
        })
    </script>
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <script type="text/javascript">
        // Get csrf from cookie
        function getCookie(name) {
            let cookieValue = null;
            if (document.cookie && document.cookie !== '') {
                const cookies = document.cookie.split(';');
                for (let i = 0; i < cookies.length; i++) {
                    const cookie = cookies[i].trim();
                    // Does this cookie string begin with the name we want?
                    if (cookie.substring(0, name.length + 1) === (name + '=')) {
                        cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                        break;
                    }
                }
            }
            return cookieValue;
        }
            

        $('.friend').click(function(e) {
            var data = { id: parseInt(e.target.id) };
            var options = {
                method: 'POST',
                headers: {
                     "X-CSRFToken": getCookie("csrftoken"),
                     'Content-Type': 'application/json'
                },
                body: JSON.stringify(data)
            };
            // console.log(options);
            $('.chat_box').empty();
            var html_data = fetch("{% url 'chat_room:chat_person' %}", options)
                                .then(function (response) {
                                    // The API call was successful!
                                    return response.text();
                                }).then(function (html) {
                                    // This is the HTML from our response as a text string
                                    // console.log(html);
                                    $('.chat_box').append(html);
                                }); 
        });
    </script>
{% endblock %}

chat_app/chat_room/templates/chat_room/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
     <style type="text/css">
        input {
            margin-top: 4px;
            text-align: center;
        }
    </style> {% endcomment %}
</head>
<body>
    <div style="height: 100vh" class='d-flex justify-content-center align-items-center'>
        <form action="{% url 'chat_room:chat_person' %}" method="post">
            {% csrf_token %}
            <input placeholder="Enter email" class='form-control' type="text" name='email'>
            <input placeholder="Enter your name" class='form-control' type="text" name='name'>
            <div class='d-flex justify-content-center'>
                <input class='btn btn-primary' type="submit" value='Chat'>
            </div>
        </form>
    </div>
</body>
</html>

chat_app/chat_room/templates/chat_room/results.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    Search Results
{% endblock title %}

{% block css_file %}
<link rel="stylesheet" href="{% static 'chat_room/results.css' %}">
{% endblock css_file %}


{% block body %}
    
    <div id='wrapper' class='search-results'>
        <h2>Search Results</h2>
        {% for user in user_list %}
            {% if not user in request.user.friends.all %}
                <div class='friend-wrapper'>
                    <div class="img">
                        <img src="/media/{{ user.profile_pic }}" alt="">                    
                    </div>
                    <div class='left'>
                        <div class="one"><p>{{ user.get_full_name }}</p></div>
                        <p>
                            <strong>{{ user.email }}</strong>
                        </p>
                    </div>
                    <div class='right'>
                        <a class='btn btn-primary' href="{% url 'main:send_friend_request' userID=user.id %}">Send friend request</a>
                    </div>
                </div>
            {% else %}
                
                <div class='friend-wrapper'>
                    <div class="img">
                        <img src="/media/{{ user.profile_pic }}" alt="">                    
                    </div>
                    <div class='left'>
                        <div class="one"><p>{{ user.get_full_name }}</p></div>
                        <p>
                            <strong>{{ user.email }}</strong>
                        </p>
                    </div>
                    <div class='right'>
                        <a class='btn btn-danger' href="{% url 'main:send_friend_request' userID=user.id %}">Friends!</a>
                    </div>
                </div>
            {% endif %}
        {% empty %}
            <h5>There is no user with such name/email. Please try again</h5>
        {% endfor %}
    </div>
{% endblock body %}

chat_app/chat_room/templates/chat_room/temp.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
    <!-- <h2>{{ file.file.url }}</h2>
    <img src="media/file/{{ file }}"> -->

    <div class="card rounded border border-info" style="width: 22rem; height: auto ; background-color: rgb(75, 168, 255);">
        <div class="card-body">
            <p>
            <h6>{{file}}</h8>
            <button type="button" class="btn btn-primary">
            <a href=src="media/file/{{ file }}"">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="white" class="bi bi-download" viewBox="0 0 16 16">
                    <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5z"/>
                    <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708l3 3z"/>
                  </svg>
            </a>
            </button>
            </p>
        </div>
    </div>

</body>
</html>

chat_app/chat_room/templates/chat_room/upload.html
{% extends 'base.html' %}

{% block title %}
    upload
{% endblock title %}

{% block body %}

<div  id="sendfile" role="dialog" class="rounded border border-info">
  <div class="modal-dialog">
  
  <!-- Modal content-->
  <div class="modal-content">

    <div class="modal-header">
      <h4 class="modal-title">Upload</h4>
    </div>
    <div class="modal-body">
      <form method="post" action="{% url 'chat_room:upload' %}" enctype="multipart/form-data">
          {% csrf_token %}
          <label>Select file....</label>
          <input type="file" class="form-control" id="doc" name="doc" required>
          <div class="modal-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
          </div>
      </form>
    </div>
  </div>

  </div>
</div>


<!-- <div class="modal" id="sendfile" role="dialog">
  <div class="modal-dialog"> -->
  
  <!-- Modal content-->
    <!-- <div class="modal-content">
      <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal">&times;</button>
      <h4 class="modal-title">Modal Header</h4>
      </div>
      <div class="modal-body">
      <p>Some text in the modal.</p>
      </div>
      <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
  </div>
  
  </div>
</div> -->


{% endblock body %} 